// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwZAPsG814EMofZqRwud8vfmuI-BMbo_U',
    appId: '1:987473501921:web:c37496777da3072216a1a0',
    messagingSenderId: '987473501921',
    projectId: 'test-e3c5d',
    authDomain: 'test-e3c5d.firebaseapp.com',
    storageBucket: 'test-e3c5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMva8hU02yNpLhgrpUIcS3nvUORNVDvak',
    appId: '1:987473501921:android:a85c26b180d7298f16a1a0',
    messagingSenderId: '987473501921',
    projectId: 'test-e3c5d',
    storageBucket: 'test-e3c5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtSQhysvARMzsESFjX3TGa0F7TbA0d-b8',
    appId: '1:987473501921:ios:c414b2fe1acec6d016a1a0',
    messagingSenderId: '987473501921',
    projectId: 'test-e3c5d',
    storageBucket: 'test-e3c5d.appspot.com',
    iosClientId: '987473501921-p4lvc0mqihjb2b0886krkactiqb8i1gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtSQhysvARMzsESFjX3TGa0F7TbA0d-b8',
    appId: '1:987473501921:ios:c414b2fe1acec6d016a1a0',
    messagingSenderId: '987473501921',
    projectId: 'test-e3c5d',
    storageBucket: 'test-e3c5d.appspot.com',
    iosClientId: '987473501921-p4lvc0mqihjb2b0886krkactiqb8i1gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
